[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 921600
board_build.f_cpu = 160000000L
build_flags = 
    -DWIFI_SSID=\"Rede\"
    -DWIFI_PASSWORD=\"arthur12345\"
    -DAPI_KEY=\"BG6PWGBS16E0S58D\"